// <auto-generated />
using GeekShopping.CartAPI.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeekShopping.CartAPI.Migrations
{
    [DbContext(typeof(PostgreSQLContext))]
    [Migration("20230628144600_TbCartHeaderDropNotNullFromCouponCode")]
    partial class TbCartHeaderDropNotNullFromCouponCode
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
